name: elimuconnect_design_system
description: Design system package for ElimuConnect
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  elimuconnect_shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
