// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRLOdXw9SDVIdVC3b6EtlU_t35Gw9b1yY',
    appId: '1:886456584154:web:8fbf3c2e6878e18fb562e3',
    messagingSenderId: '886456584154',
    projectId: 'elimuconnect-e0858',
    authDomain: 'elimuconnect-e0858.firebaseapp.com',
    storageBucket: 'elimuconnect-e0858.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmhj_2cMsxMWgw5Ej6J41GKXUZZRo25zk',
    appId: '1:886456584154:android:e8ded48e190a868cb562e3',
    messagingSenderId: '886456584154',
    projectId: 'elimuconnect-e0858',
    storageBucket: 'elimuconnect-e0858.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySBC37whEpJSHcLkVUbKNDURX_MzWMkk',
    appId: '1:886456584154:ios:0685cb3ac954663bb562e3',
    messagingSenderId: '886456584154',
    projectId: 'elimuconnect-e0858',
    storageBucket: 'elimuconnect-e0858.firebasestorage.app',
    iosBundleId: 'com.example.elimuConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCySBC37whEpJSHcLkVUbKNDURX_MzWMkk',
    appId: '1:886456584154:ios:0685cb3ac954663bb562e3',
    messagingSenderId: '886456584154',
    projectId: 'elimuconnect-e0858',
    storageBucket: 'elimuconnect-e0858.firebasestorage.app',
    iosBundleId: 'com.example.elimuConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRLOdXw9SDVIdVC3b6EtlU_t35Gw9b1yY',
    appId: '1:886456584154:web:1a0e3d9fdb998483b562e3',
    messagingSenderId: '886456584154',
    projectId: 'elimuconnect-e0858',
    authDomain: 'elimuconnect-e0858.firebaseapp.com',
    storageBucket: 'elimuconnect-e0858.firebasestorage.app',
  );
}
