name: elimuconnect_shared
description: Shared models and utilities for ElimuConnect
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.6
