# File: packages/app/pubspec.yaml

name: elimuconnect_app
description: ElimuConnect educational platform - mobile and web application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^12.1.3
  auto_route: ^7.8.4

  # HTTP & API
  dio: ^5.3.3
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  animate_do: ^3.1.2
  lottie: ^2.7.0

  # Utilities
  connectivity_plus: ^5.0.1
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.1.0
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  crypto: ^3.0.3
  intl: ^0.18.1
  uuid: ^4.2.1

  # File handling
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  mime: ^1.0.4
  image_picker: ^1.0.4

  # Video & Media
  video_player: ^2.8.1
  chewie: ^1.7.4
  just_audio: ^0.9.36

  # PDF & Documents
  flutter_pdfview: ^1.3.2
  printing: ^5.11.1

  # Forms & Validation
  reactive_forms: ^16.1.1
  mask_text_input_formatter: ^2.5.0

  # Development
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Testing
  mockito: ^5.4.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
