name: elimuconnect_app
description: ElimuConnect - Educational Platform for Kenya
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  
  # Local packages
  elimuconnect_design_system:
    path: ../design_system
  elimuconnect_shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
