name: elimuconnect_app
description: ElimuConnect - Educational Platform for Kenya
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  dio: ^5.3.3
  connectivity_plus: ^5.0.2
  
  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Navigation
  go_router: ^12.1.3
  
  # File Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  
  # Notifications
  flutter_local_notifications: ^16.3.3
  timezone: ^0.9.2
  permission_handler: ^11.1.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  crypto: ^3.0.3
  
  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    - assets/config/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
