name: elimuconnect
repository: https://github.com/manodhiambo/elimu_connect

packages:
  - packages/**

command:
  version:
    workspaceChangelog: false
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.10.0"

scripts:
  analyze:
    exec: dart analyze .
    description: Run analysis for all packages.

  test:
    run: melos exec --fail-fast -- "dart test"
    description: Run all Dart tests in all packages.

  test:flutter:
    run: melos exec --fail-fast --flutter --dir-exists="test" -- "flutter test"
    description: Run Flutter tests.

  gen:
    run: melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"
    description: Generate code for packages with build_runner.

  build:app:
    run: melos exec --scope="elimuconnect_app" -- "flutter build apk --release"
    description: Build Flutter app.

  clean:deep:
    run: |
      melos clean
      find . -name "pubspec_overrides.yaml" -delete
      find . -name ".dart_tool" -exec rm -rf {} +
      find . -name "build" -exec rm -rf {} +
    description: Deep clean all packages.

  web:
    run: |
      melos exec --scope="elimuconnect_app" -- \
        "flutter build web && cd build/web && python3 -m http.server 8080"
    description: Build and serve the Flutter web app at http://localhost:8080.

  web:dev:
    run: melos exec --scope="elimuconnect_app" -- "flutter run -d chrome"
    description: Run the Flutter web app in Chrome with hot reload.
