class KenyaCurriculum {
  static const Map<String, List<String>> cbcSubjects = {
    'pp1': [
      'Language Activities',
      'Mathematical Activities',
      'Environmental Activities',
      'Psychomotor and Creative Activities',
    ],
    'pp2': [
      'Language Activities',
      'Mathematical Activities',
      'Environmental Activities',
      'Psychomotor and Creative Activities',
    ],
    'grade_1': [
      'English Language',
      'Kiswahili Language',
      'Indigenous Language',
      'Mathematical Activities',
      'Environmental Activities',
      'Hygiene and Nutrition Activities',
      'Religious Education',
      'Movement and Creative Activities',
    ],
    'grade_2': [
      'English Language',
      'Kiswahili Language',
      'Indigenous Language',
      'Mathematical Activities',
      'Environmental Activities',
      'Hygiene and Nutrition Activities',
      'Religious Education',
      'Movement and Creative Activities',
    ],
    'grade_3': [
      'English Language',
      'Kiswahili Language',
      'Indigenous Language',
      'Mathematical Activities',
      'Environmental Activities',
      'Hygiene and Nutrition Activities',
      'Religious Education',
      'Movement and Creative Activities',
    ],
    'grade_4': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Science and Technology',
      'Social Studies',
      'Religious Education',
      'Creative Arts',
      'Physical and Health Education',
    ],
    'grade_5': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Science and Technology',
      'Social Studies',
      'Religious Education',
      'Creative Arts',
      'Physical and Health Education',
    ],
    'grade_6': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Science and Technology',
      'Social Studies',
      'Religious Education',
      'Creative Arts',
      'Physical and Health Education',
    ],
    'grade_7': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Integrated Science',
      'Health Education',
      'Pre-Technical Studies',
      'Social Studies',
      'Religious Education',
      'Creative Arts and Sports',
    ],
    'grade_8': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Integrated Science',
      'Health Education',
      'Pre-Technical Studies',
      'Social Studies',
      'Religious Education',
      'Creative Arts and Sports',
    ],
    'grade_9': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Integrated Science',
      'Health Education',
      'Pre-Technical Studies',
      'Social Studies',
      'Religious Education',
      'Creative Arts and Sports',
    ],
    'form_1': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Biology',
      'Chemistry',
      'Physics',
      'History and Government',
      'Geography',
      'Christian Religious Education',
      'Islamic Religious Education',
      'Hindu Religious Education',
      'Computer Studies',
      'Business Studies',
      'Agriculture',
      'Home Science',
      'Art and Design',
      'Music',
      'French',
      'German',
      'Arabic',
    ],
    'form_2': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Biology',
      'Chemistry',
      'Physics',
      'History and Government',
      'Geography',
      'Christian Religious Education',
      'Islamic Religious Education',
      'Hindu Religious Education',
      'Computer Studies',
      'Business Studies',
      'Agriculture',
      'Home Science',
      'Art and Design',
      'Music',
      'French',
      'German',
      'Arabic',
    ],
    'form_3': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Biology',
      'Chemistry',
      'Physics',
      'History and Government',
      'Geography',
      'Christian Religious Education',
      'Islamic Religious Education',
      'Hindu Religious Education',
      'Computer Studies',
      'Business Studies',
      'Agriculture',
      'Home Science',
      'Art and Design',
      'Music',
      'French',
      'German',
      'Arabic',
    ],
    'form_4': [
      'English',
      'Kiswahili',
      'Mathematics',
      'Biology',
      'Chemistry',
      'Physics',
      'History and Government',
      'Geography',
      'Christian Religious Education',
      'Islamic Religious Education',
      'Hindu Religious Education',
      'Computer Studies',
      'Business Studies',
      'Agriculture',
      'Home Science',
      'Art and Design',
      'Music',
      'French',
      'German',
      'Arabic',
    ],
  };

  static const Map<String, String> subjectCodes = {
    'English': '101',
    'Kiswahili': '102',
    'Mathematics': '121',
    'Biology': '231',
    'Chemistry': '233',
    'Physics': '232',
    'History and Government': '311',
    'Geography': '312',
    'Christian Religious Education': '313',
    'Islamic Religious Education': '314',
    'Hindu Religious Education': '315',
    'Computer Studies': '451',
    'Business Studies': '565',
    'Agriculture': '443',
    'Home Science': '442',
    'Art and Design': '444',
    'Music': '445',
    'French': '503',
    'German': '504',
    'Arabic': '505',
  };

  static List<String> getSubjectsForGrade(String grade) {
    return cbcSubjects[grade] ?? [];
  }

  static String? getSubjectCode(String subject) {
    return subjectCodes[subject];
  }

  static bool isValidSubjectForGrade(String subject, String grade) {
    final subjects = getSubjectsForGrade(grade);
    return subjects.contains(subject);
  }
}
