name: elimuconnect_backend
description: ElimuConnect Backend API Server
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Local packages
  elimuconnect_shared:
    path: ../shared

  # Server
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5

  # Database
  mongo_dart: ^0.10.5
  redis: ^3.0.1

  # Authentication
  dart_jsonwebtoken: ^2.12.1
  crypto: ^3.0.3
  bcrypt: ^1.1.3

  # File handling
  mime: ^1.0.4
  path: ^1.8.3

  # Email
  mailer: ^6.0.1

  # Utilities
  intl: ^0.19.0
  dotenv: ^4.2.0
  logging: ^1.2.0

dev_dependencies:
  test: ^1.24.6
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

executables:
  server:
