// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'admin_model.dart';

// Placeholder - will be generated by build_runner
Map<String, dynamic> _$AdminToJson(Admin instance) => <String, dynamic>{};
Admin _$AdminFromJson(Map<String, dynamic> json) => throw UnimplementedError();

// Registration request stubs
Map<String, dynamic> _$AdminRegistrationRequestToJson(AdminRegistrationRequest instance) => <String, dynamic>{};
AdminRegistrationRequest _$AdminRegistrationRequestFromJson(Map<String, dynamic> json) => throw UnimplementedError();
