// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'parent_model.dart';

// Placeholder - will be generated by build_runner
Map<String, dynamic> _$ParentToJson(Parent instance) => <String, dynamic>{};
Parent _$ParentFromJson(Map<String, dynamic> json) => throw UnimplementedError();

// Registration request stubs
Map<String, dynamic> _$ParentRegistrationRequestToJson(ParentRegistrationRequest instance) => <String, dynamic>{};
ParentRegistrationRequest _$ParentRegistrationRequestFromJson(Map<String, dynamic> json) => throw UnimplementedError();
