// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'student_model.dart';

// Placeholder - will be generated by build_runner
Map<String, dynamic> _$StudentToJson(Student instance) => <String, dynamic>{};
Student _$StudentFromJson(Map<String, dynamic> json) => throw UnimplementedError();

// Registration request stubs
Map<String, dynamic> _$StudentRegistrationRequestToJson(StudentRegistrationRequest instance) => <String, dynamic>{};
StudentRegistrationRequest _$StudentRegistrationRequestFromJson(Map<String, dynamic> json) => throw UnimplementedError();
