// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'teacher_model.dart';

// Placeholder - will be generated by build_runner
Map<String, dynamic> _$TeacherToJson(Teacher instance) => <String, dynamic>{};
Teacher _$TeacherFromJson(Map<String, dynamic> json) => throw UnimplementedError();

// Registration request stubs
Map<String, dynamic> _$TeacherRegistrationRequestToJson(TeacherRegistrationRequest instance) => <String, dynamic>{};
TeacherRegistrationRequest _$TeacherRegistrationRequestFromJson(Map<String, dynamic> json) => throw UnimplementedError();
